### ISSUE TITLE
What are the PostrgreSQL Tables? 

### ISSUE THREAD

**Issue by TrissieTheHusky** [Willy-C/SnowflakeBot#2]
I'm confused could you elaborate on creating tables instead of just saying create tables. Cause there is other options on creating tables creating a table ex:
```
CREATE TABLE table_name (
	column_name TYPE column_constraint,
	table_constraint table_constraint
) INHERITS existing_table_name;
```

**Comment by Rinume-chan** [comment]
Hello, you can see the current db schema [here](https://github.com/Willy-C/SnowflakeBot/blob/8031a12f19c71fe2838f6d9b6f84615e3420e82b/data/schema.sql)

**Comment by TrissieTheHusky** [comment]
Thank you so much. If you ever need a contributor, I will help out as much as I can.
